### ISSUE TITLE
uint256.FromHex() with leading zeroes is inconsistent

### ISSUE THREAD

**Issue by MastaP** [holiman/uint256#117]
Hi, 

We have a problem converting hash values into `uint256` as `uint256.FromHex()` does not accept hex values with leading zeroes. Is there a particular reason for this?
Why do I think this behavior is inconsistent? I can easily convert byte array with leading zeroes to uint256:
```
uint256.NewInt(0).SetBytes([]byte{0x00, 0x01})
```
It would be nice to be able to covert using `FromHex()` directly without intermediate manipulations.
Thanks

**Comment by holiman** [comment]
That's due to historic reasons, to make it a drop-in replacement in go-ethereum. For some old reason I don't know, leading zeroes is disallowed. 
However, if you want to convert from a hash, you can use e.g. `new(uint256.Int).SetBytes32`, and not use the hex format at all. 

I'll close this issue, because it's something that will not be fixed -- we're going to have to live with it for legacy reasons. 

oh, and sorry for taking so long in responding!
